echo 1million
./make_vector 1000000 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 1 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 8 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 36 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 72 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 144 vector.out
rm vector.out
echo 10million
./make_vector 10000000 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 1 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 8 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 36 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 72 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 144 vector.out
rm vector.out
echo 100million
./make_vector 100000000 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 1 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 8 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 36 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 72 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 144 vector.out
rm vector.out
echo 1billion
./make_vector 1000000000 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 1 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 8 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 36 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 72 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 144 vector.out
rm vector.out
echo 10billion
./make_vector 10000000000 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 1 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 8 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 36 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 72 vector.out
perf stat -e branch-instructions,branch-misses,cache-misses,cache-references,context-switches,cpu-clock,faults,task-clock,cycles,instructions,stalled-cycles-backend,stalled-cycles-frontend,L1-dcache-load-misses,L1-dcache-loads,L1-icache-load-misses,L1-icache-loads,LLC-load-misses,LLC-loads,dTLB-load-misses,dTLB-loads,iTLB-load-misses,iTLB-loads ./load_vector_test_thr 144 vector.out
rm vector.out




